md_core_home:
    path:    /
    defaults:
         _controller: MDCoreBundle:Home:home

md_core_admin_home:
    path: /admin
    defaults:
        _controller: MDCoreBundle:Admin:home

md_core_admin_list_articles_news:
    path: /admin/listnews/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:listNews
        batch: 20
        page: 0 
    requirements:
        batch: \d+
        page: \d+

md_core_admin_list_game_function:
    path: /admin/gamefunctions
    defaults:
        _controller: MDCoreBundle:Admin:listGameFunction
 
md_core_contact:
    path:    /contact
    defaults: { _controller: MDCoreBundle:Contact:contact }

md_core_news_viewbatch:
    path:    /articles/news/batch/{batch}/{page}
    defaults: 
        _controller: MDCoreBundle:NewsBundle:viewBatch
        batch: 5
        page: 0
    requirements:
        batch: \d+
        page:  \d*

md_core_news_view:
    path:    /articles/news/view/{id}
    defaults:
        _controller: MDCoreBundle:NewsBundle:view
    requirements:
        id: \d+
        
md_core_news_create:
    path:    /admin/articles/news/create
    defaults:
        _controller: MDCoreBundle:NewsBundle:create

md_core_news_edit:
    path:    /admin/articles/news/edit/{id}
    defaults:
        _controller: MDCoreBundle:NewsBundle:edit
    requirements:
        id: \d+

md_core_news_delete:
    path:    /admin/articles/news/delete/{id}
    defaults:
        _controller: MDCoreBundle:NewsBundle:delete
    requirements:
        id: \d+

md_core_category_viewbatch:
    path:    /category/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:CategoryBundle:viewBatch
        batch: 10
        page: 0
    requirements:
        batch: \d+
        page: \d*

md_core_category_view:
    path:    /category/view/{id}
    defaults:
        _controller: MDCoreBundle:CategoryBundle:view
    requirements:
        id: \d+

md_core_category_create:
    path:    /admin/category/create
    defaults:
        _controller: MDCoreBundle:CategoryBundle:create
    requirements:
        id: \d+

md_core_category_edit:
    path:    /admin/category/edit/{id}
    defaults:
        _controller: MDCoreBundle:CategoryBundle:edit
    requirements:
        id: \d+

md_core_category_delete:
    path:    /admin/category/delete/{id}
    defaults:
        _controller: MDCoreBundle/CategoryBundle:delete
    requirements:
        id: \d+

md_core_game_genre_viewbatch:
    path:    /game/genre/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:GenreBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_genre_view:
    path:     /game/genre/view/{id}
    defaults: { _controller: MDCoreBundle:GenreBundle:view }
    requirements:
        id: \d+

md_core_game_genre_create:
    path:    /admin/game/genre/create
    defaults:
        _controller: MDCoreBundle:GenreBundle:create

md_core_game_genre_edit:
    path:    /admin/game/genre/edit/{id}
    defaults:
        _controller: MDCoreBundle:GenreBundle:edit
    requirements:
        id: \d+

md_core_game_genre_delete:
    path:    /admin/game/genre/delete/{id}
    defaults:
        _controller: MDCoreBundle:GenreBundle:delete
    requirements:
        id: \d+
md_core_game_theme_viewbatch:
    path:    /game/theme/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:ThemeBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_theme_view:
    path:     /game/theme/view/{id}
    defaults: { _controller: MDCoreBundle:ThemeBundle:view }
    requirements:
        id: \d+

md_core_game_theme_create:
    path:    /admin/game/theme/create
    defaults:
        _controller: MDCoreBundle:ThemeBundle:create

md_core_game_theme_edit:
    path:    /admin/game/theme/edit/{id}
    defaults:
        _controller: MDCoreBundle:ThemeBundle:edit
    requirements:
        id: \d+

md_core_game_theme_delete:
    path:    /admin/game/theme/delete/{id}
    defaults:
        _controller: MDCoreBundle:ThemeBundle:delete
    requirements:
        id: \d+
md_core_game_plateforme_viewbatch:
    path:    /game/plateforme/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:PlateformeBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_plateforme_view:
    path:     /game/plateforme/view/{id}
    defaults: { _controller: MDCoreBundle:PlateformeBundle:view }
    requirements:
        id: \d+

md_core_game_plateforme_create:
    path:    /admin/game/plateforme/create
    defaults:
        _controller: MDCoreBundle:PlateformeBundle:create

md_core_game_plateforme_edit:
    path:    /admin/game/plateforme/edit/{id}
    defaults:
        _controller: MDCoreBundle:PlateformeBundle:edit
    requirements:
        id: \d+

md_core_game_plateforme_delete:
    path:    /admin/game/plateforme/delete/{id}
    defaults:
        _controller: MDCoreBundle:PlateformeBundle:delete
    requirements:
        id: \d+
md_core_game_licence_viewbatch:
    path:    /game/licence/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:LicenceBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_licence_view:
    path:     /game/licence/view/{id}
    defaults: { _controller: MDCoreBundle:LicenceBundle:view }
    requirements:
        id: \d+

md_core_game_licence_create:
    path:    /admin/game/licence/create
    defaults:
        _controller: MDCoreBundle:LicenceBundle:create

md_core_game_licence_edit:
    path:    /admin/game/licence/edit/{id}
    defaults:
        _controller: MDCoreBundle:LicenceBundle:edit
    requirements:
        id: \d+

md_core_game_licence_delete:
    path:    /admin/game/licence/delete/{id}
    defaults:
        _controller: MDCoreBundle:LicenceBundle:delete
    requirements:
        id: \d+
md_core_game_market_viewbatch:
    path:    /game/market/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:MarketBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_market_view:
    path:     /game/market/view/{id}
    defaults: { _controller: MDCoreBundle:MarketBundle:view }
    requirements:
        id: \d+

md_core_game_market_create:
    path:    /admin/game/market/create
    defaults:
        _controller: MDCoreBundle:MarketBundle:create

md_core_game_market_edit:
    path:    /admin/game/market/edit/{id}
    defaults:
        _controller: MDCoreBundle:MarketBundle:edit
    requirements:
        id: \d+

md_core_game_market_delete:
    path:    /admin/game/market/delete/{id}
    defaults:
        _controller: MDCoreBundle:MarketBundle:delete
    requirements:
        id: \d+
md_core_game_publisher_viewbatch:
    path:    /game/publisher/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:PublisherBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_publisher_view:
    path:     /game/publisher/view/{id}
    defaults: { _controller: MDCoreBundle:PublisherBundle:view }
    requirements:
        id: \d+

md_core_game_publisher_create:
    path:    /admin/game/publisher/create
    defaults:
        _controller: MDCoreBundle:PublisherBundle:create

md_core_game_publisher_edit:
    path:    /admin/game/publisher/edit/{id}
    defaults:
        _controller: MDCoreBundle:PublisherBundle:edit
    requirements:
        id: \d+

md_core_game_publisher_delete:
    path:    /admin/game/publisher/delete/{id}
    defaults:
        _controller: MDCoreBundle:PublisherBundle:delete
    requirements:
        id: \d+
md_core_game_developer_viewbatch:
    path:    /game/developer/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:DeveloperBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_developer_view:
    path:     /game/developer/view/{id}
    defaults: { _controller: MDCoreBundle:DeveloperBundle:view }
    requirements:
        id: \d+

md_core_game_developer_create:
    path:    /admin/game/developer/create
    defaults:
        _controller: MDCoreBundle:DeveloperBundle:create

md_core_game_developer_edit:
    path:    /admin/game/developer/edit/{id}
    defaults:
        _controller: MDCoreBundle:DeveloperBundle:edit
    requirements:
        id: \d+

md_core_game_developer_delete:
    path:    /admin/game/developer/delete/{id}
    defaults:
        _controller: MDCoreBundle:DeveloperBundle:delete
    requirements:
        id: \d+
md_core_game_game_viewbatch:
    path:    /game/game/batch/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:GameBundle:viewBatch
        batch: 5
        page:  0
    requirements:
        batch: \d+
        page:  \d*

md_core_game_game_view:
    path:     /game/game/view/{id}
    defaults: { _controller: MDCoreBundle:GameBundle:view }
    requirements:
        id: \d+

md_core_game_game_create:
    path:    /admin/game/game/create
    defaults:
        _controller: MDCoreBundle:GameBundle:create

md_core_game_game_edit:
    path:    /admin/game/game/edit/{id}
    defaults:
        _controller: MDCoreBundle:GameBundle:edit
    requirements:
        id: \d+

md_core_game_game_delete:
    path:    /admin/game/game/delete/{id}
    defaults:
        _controller: MDCoreBundle:GameBundle:delete
    requirements:
        id: \d+

md_core_admin_game_games:
    path: /admin/game/game/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gameGames
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_genres:
    path: /admin/game/genre/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gameGenres
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_themes:
    path: /admin/game/themes/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gameThemes
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_licences:
    path: /admin/game/licences/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gameLicences
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_developers:
    path: /admin/game/developers/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gameDevelopers
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_publishers:
    path: /admin/game/publishers/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gamePublishers
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_markets:
    path: /admin/game/markets/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gameMarkets
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_plateformes:
    path: /admin/game/plateformes/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gamePlateformes
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+

md_core_admin_game_games:
    path: /admin/game/game/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:gameGames
        batch: 20
        page: 0
    requirements:
        batch: \d+
        page: \d+
