md_core_home:
    path:    /
    defaults:
         _controller: MDCoreBundle:Home:home

md_core_admin_home:
    path: /admin
    defaults:
        _controller: MDCoreBundle:Admin:home

md_core_admin_list_articles_news:
    path: /admin/listnews/{batch}/{page}
    defaults:
        _controller: MDCoreBundle:Admin:listNews
        batch: 20
        page: 0 
    requirements:
        batch: \d+
        page: \d+

md_core_admin_list_game_function:
    path: /admin/gamefunctions
    defaults:
        _controller: MDCoreBundle:Admin:listGameFunction
 
md_core_contact:
    path:    /contact
    defaults: { _controller: MDCoreBundle:Contact:contact }

