md_category_create:
    path:     /admin/category/create
    defaults: { _controller: MDCategoryBundle:Category:Category }

md_category_edit:
    path:    /admin/category/edit/{id}
    defaults: { _controller: MDCategoryBundle:Category:Category }
    requirements:
        id: \d+

md_category_view:
    path:    /category/view/{id}
    defaults: { _controller: MDCategory:Category:Category }
    requirements:
        id: \d+

md_category_delete:
    path:    /admin/category/delete/{id}
    defaults: { _controller: MDCategory:Category:Category }
    requirements:
        id: \d+
