md_category_create:
    path:     /admin/cat/c
    defaults: { _controller: MDCategoryBundle:Category:Category }

md_category_edit:
    path:    /admin/cat/e/{id}
    defaults: { _controller: MDCategoryBundle:Category:Category }
    requirements:
        id: \d+

md_category_view:
    path:    /cat/v/{id}
    defaults: { _controller: MDCategory:Category:Category }
    requirements:
        id: \d+

md_category_delete:
    path:    /admin/cat/d/{id}
    defaults: { _controller: MDCategory:Category:Category }
    requirements:
        id: \d+
