services:
#    md_tags.example:
#        class: MDTagsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    md_tags.form.type.tag:
        class: MDTagsBundle\Form\TagsSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }