md_comment_batch:
    path:    /comment/comment/batch/{batch}/{page}
    defaults:
        _controller: MDCommentBundle:Comment:batch
        batch: 10
        page: 0
    requirements:
        batch: \d+
        page: \d

md_comment_view:
    path:    /comment/comment/view/{comment_id}
    defaults:
        _controller: MDCommentBundle:Comment:view
    requirements:
        comment_id: \d+

md_comment_create:
    path:    /admin/comment/comment/create
    defaults:
        _controller: MDCommentBundle:Comment:create

md_comment_edit:
    path:    /admin/comment/comment/edit/{comment_id}
    defaults:
        _controller: MDCommentBundle:Comment:edit
    requirements:
        comment_id: \d+

md_comment_delete:
    path:    /admin/comment/comment/delete/{comment_id}
    defaults:
        _controller: MDCommentBundle:Comment:delete
    requirements:
        comment_id: \d+
