md_article_batch_by_category:
    path:    /article/article/batch/{batch}/{page}/{category}/{parent}
    defaults:
        _controller: MDArticleBundle:Article:batchByCategory
        batch: 10
        page: 0
    requirements:
        batch: \d+
        page: \d
        category: news|jeux-video|dossier|analyse|livre|critique|general|edito|science-fiction|autres
        parent: general|jeux-video|livre|null

md_article_batch_all:
    path:    /admin/article/article/batch/{batch}/{page}/{category}
    defaults:
        _controller: MDArticleBundle:Article:batch
        batch: 10
        page: 0
        category: all
    requirements:
        batch: \d+
        page: \d
        category: jeux-video|news|critique_jv|dossier|analyse|livre|critique_livre|all

md_article_view:
    path:    /article/article/view/{article_id}
    defaults:
        _controller: MDArticleBundle:Article:view
    requirements:
        article_id: \d+

md_article_create:
    path:    /admin/article/article/create/
    defaults:
        _controller: MDArticleBundle:Article:create

md_article_edit:
    path:    /admin/article/article/edit/{article_id}
    defaults:
        _controller: MDArticleBundle:Article:edit
    requirements:
        article_id: \d+

md_article_delete:
    path:    /admin/article/article/delete/{article_id}
    defaults:
        _controller: MDArticleBundle:Article:delete
    requirements:
        article_id: \d+
