md_articles_view:
    path: /article/news/view/{news_id}
    defaults:
        _controller: MDArticlesBundle:News:view
    requirements:
        news_id: \d+

md_articles_create:
    path: /admin/article/news/create
    defaults:
        _controller: MDArticlesBundle:News:create

md_articles_edit:
    path: /admin/article/news/edit/{id}
    defaults: { _controller: MDArticlesBundle:News:edit}
    requirements:
        id: \d+

md_articles_delete:
    path: /admin/article/news/delete/{id}
    defaults: { _controller: MDArticlesBundle:News:delete}
    requirements:
        id: \d+
md_test_view:
    path:    /article/test/view/{test_id}
    defaults:
        _controller: MDArticlesBundle:Test:view
    requirements:
        test_id: \d+

md_test_create:
    path:    /admin/article/test/create
    defaults:
        _controller: MDArticlesBundle:Test:create

md_test_edit:
    path:    /admin/article/test/edit/{test_id}
    defaults:
        _controller: MDArticlesBundle:Test:edit
    requirements:
        test_id: \d+

md_test_delete:
    path:    /admin/article/test/delete/{test_id}
    defaults:
        _controller: MDArticlesBundle:Test:delete
    requirements:
        test_id: \d+
