md_articles_view:
    path: /n/v/{news_id}
    defaults:
        _controller: MDArticlesBundle:News:view
    requirements:
        news_id: \d+

md_articles_create:
    path: /admin/n/c
    defaults:
        _controller: MDArticlesBundle:News:create

md_articles_edit:
    path: /admin/n/e/{id}
    defaults: { _controller: MDArticlesBundle:News:edit}
    requirements:
        id: \d+

md_articles_delete:
    path: /admin/n/d/{id}
    defaults: { _controller: MDArticlesBundle:News:delete}
    requirements:
        id: \d+
