MDArticlesBundle\Entity\News:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
    properties:
        dateCreation:
            - DateTime: ~
        title:
            - NotBlank: ~
        content:
            - NotBlank: ~
        datePublication:
            - DateTime: ~
        updatedAt:
            - DateTime: ~
