services:
#    md_paging.example:
#        class: MDPagingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    md_paging.paging:
        class: MDPagingBundle\Paging\Paging
        arguments: ["@doctrine.orm.entity_manager"]
